spring.datasource.username: 'kraykov'
spring.datasource.password: ENC(ZPFBvfhMlH9zTI/UYhLBX2vHIpKPwKTw)
spring.datasource.driver-class-name: com.mysql.jdbc.Driver

spring.http.multipart.max-file-size: 3000000
spring.http.multipart.max-request-size: 3000000

server:
  port : 8093

security:
  jwt:
    token:
      secret-key: ENC(oOMhast5nvsa0og/3esr8/BNoa2i6FO0)
      expire-length: 90000000

services:
    user:
      loginUser: http://localhost:8071/users/login
      signupUser: http://localhost:8071/users/signup
      getUserById: http://localhost:8071/users/{userId}
      updateUserPassword: http://localhost:8071/users/password/{userId}
      createTrainer: http://localhost:8071/users/trainer
      getTrainerByUserId: http://localhost:8071/users/trainer/{userId}
      createClient: http://localhost:8071/users/client
      getClientByUserId: http://localhost:8071/users/client/{userId}
      getAccessModules: http://localhost:8071/access/modules
      insertAccessModules: http://localhost:8071/access/modules
      insertUserPermissions: http://localhost:8071/access/access/{userId}/permissions
      getCities: http://localhost:8071/cities
    media:
      setAvatar: http://localhost:8072/media/avatar/{userId}


---
spring:
  profiles: dev
  datasource.url: 'jdbc:mysql://home.micro3x.com:4404/kirodb'

---
spring:
  profiles: prod
  datasource.url: 'jdbc:mysql://192.168.9.5:3306/kirodb'





